orocos_kdl:
    build_code: |
        # Fix hard-coded /usr/local path for eigen3
        reinplace "s|/usr/local/include/eigen3|${prefix}/include/eigen3|g" ${worksrcpath}/config/FindEigen3.cmake
xmlrpcpp:
    top_level: |
        # Doesnt compile with clang
        configure.compiler macports-gcc-4.8
roscpp_traits:
    build_code: |
        # Forward declares not supported by libc++
        reinplace "s|template<typename T> class allocator;||g" ${worksrcpath}/include/ros/message_forward.h
catkin:
    build_code: |
         # Fix DYLD_LIBRARY_PATH overriding system libs
         reinplace "s|DYLD_LIBRARY_PATH|DYLD_FALLBACK_LIBRARY_PATH|g" ${worksrcpath}/cmake/templates/_setup_util.py.in
